[package]
name = "avenir"
version = "0.1.0"
authors = ["nwmqpa <thomas.nicolleŧ@epitech.eu>", "afourcat <alexandre.fourcat@epitech.eu>"]
exclude = ["examples/*"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
vulkan_backend = []
metal_backend = []
dx12_backend = []
3d-format = ["gltf", "dot_vox"]

[dependencies]
log = "0.4.0"
arrayvec = "0.4"
gfx-hal = "0.3.1"
simple_logger = "1.0"
shaderc = "0.6.1"

[dependencies.rendy]
version = "0.5.1"
features = ["base", "init-winit", "vulkan"]

[target.'cfg(target_os = "macos")'.dependencies.rendy]
version = "0.5.1"
features = ["base", "init-winit"]

[target.'cfg(windows)'.dependencies.rendy]
version = "0.5.1"
features = ["base", "init-winit", "metal"]

[dependencies.dot_vox]
version = "4.0.0"
optional = true

[dependencies.gltf]
version = "0.13"
features = ["extras", "names"]
optional = true

[[example]]
name = "triangle"
path = "examples/triangle/main.rs"

[[example]]
name = "gltf"
path = "examples/gltf/main.rs"
