[package]
name = "render-lib"
version = "0.1.0"
authors = ["nwmqpa <thomas.nicolleŧ@epitech.eu>", "afourcat <alexandre.fourcat@epitech.eu>"]
exclude = ["examples/*"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
metal = ["gfx-backend-metal"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
winit = "0.19.3"
log = "0.4.0"
arrayvec = "0.4"
gfx-hal = "0.3.1"
simple_logger = "1.0"
shaderc = "0.6.1"

[dependencies.gfx-backend-vulkan]
features = ["winit", "x11"]
version = "0.3.0"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.gfx-backend-metal]
features = ["winit"]
version = "0.3.2"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
features = ["winit"]
version = "0.3.2"
optional = true

[[example]]
name = "triangle"
path = "examples/triangle/main.rs"
